[app]
name = "faucet"
schema = "http"
host = "localhost"
port = "8080"

routePrefix = "/api"

banner = true

controllers = "./src/api/controllers/**/*Controller.ts"

[network]
[[network.substrate]]
name = "subdao"
ws = "ws://127.0.0.1:9933"
contractAddress = "abc"
abiPath = "def"
userAddress = "ght"

[log]
level = "debug"
output = "dev"